[package]
name = "bespoke-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
bytemuck = "1.14.3"
cgmath = "0.18.0"
image = "0.24.8"
wgpu = "0.19.1"
winit = "0.29.10"
